feat: Add error description in bulk delete [BACKLOG-39987]
pentaho/pentaho-scheduler-plugin pull request #151
Opened 2024-03-27 18:43 UTC by Pancho7

@pentaho/millenniumfalcon please review

2024-03-27 18:53 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-03-27 18:53 UTC, buildguy commented
### :white_check_mark: Build finished in 9m 43s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -Djs.no.sandbox -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **133**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-151/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-04-01 16:25 UTC, mbrasil commented on ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java
> +                  showHTMLMessage( Messages.getString( "error" ), Messages.getString( "bulkDeleteErrors",
Here I still think it's best to throw the error instead of showing the message

2024-04-01 16:28 UTC, mbrasil commented on ui/src/main/java/org/pentaho/mantle/client/workspace/SchedulesPanel.java
> +          String errorMessage = "- " + job.getJobName() + ": " + Messages.getString( "bulkDeletePermissionDeniedError" );
Here I think it's best to leave all the strings in the message properties and use "{0}" or similar to replace the job name. Something like this: "- {0} bulk delete msg" in the properties file.

2024-04-01 16:28 UTC, mbrasil requested changes
Could you please review these things before merging? Thank you

2024-04-01 18:12 UTC, afrjorge commented on ui/src/main/resources/org/pentaho/mantle/public/messages/schedulerMessages_en.properties
> +bulkDeleteUnknownError=Unable to delete. Please contact administrator
"(...). Please contact your Administrator." is used in other places, we can use it here also.

2024-04-01 18:13 UTC, afrjorge commented on ui/src/main/resources/org/pentaho/mantle/public/messages/schedulerMessages.properties
> +bulkDeleteUnknownError=Unable to delete. Please contact administrator
"(...). Please contact your Administrator." is used in other places, we can use it here also.

2024-04-02 17:07 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-04-02 17:07 UTC, buildguy commented
### :white_check_mark: Build finished in 8m 34s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **133**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-151/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-04-02 17:26 UTC, afrjorge approved these changes

2024-04-02 23:03 UTC, buildguy commented
<div align='center'>

[![👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://raw.githubusercontent.com/jfrog/frogbot/master/resources/v2/noVulnerabilityBannerPR.png)](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

2024-04-02 23:03 UTC, buildguy commented
### :white_check_mark: Build finished in 7m 7s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl ui
```
---
:ok_hand: All tests passed!
 
Tests run: **133**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/pentaho-scheduler-plugin/job/PR-151/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

2024-04-03 10:01 UTC, merged